"""CDN container setting.

This setting is in a separate file so it can be autogenerated during deployment.
"""

# Allows to server static files from a separate CDN server. Can be
# empty.
CDN_CONTAINER=""
